name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. v5.0.0)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JAR
        run: ./gradlew jar --info
      - name: Rename JAR
        run: |
          echo $PWD
          ls
          suffix="${{ github.event.inputs.version }}"
          updatedSuffix="${suffix//./_}"
          mv "build/libs/Dartzee.jar" "build/libs/Dartzee_$updatedSuffix.jar"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/libs/*.jar"
          commit: master
          tag: github.events.inputs.version
